services:
  pgdatabase:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maaya
    volumes:
      - "./maaya_labs_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@email.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    ports:
#      - "8080:80"
