services:
  pgdatabase:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maaya
    volumes:
      - "./maaya_labs_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  run:
    image: "maaya-labs"
    depends_on:
      pgdatabase:
        condition: service_healthy
    volumes:
      - .:/app
    command: python3 src/etl.py

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@email.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    ports:
#      - "8080:80"
